<?php

/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/


	File: qa-include/qa-lang-admin.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases for admin center

	Indonesian translation: Ivan Lanin <ivan at bahtera dot org>


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'active_widgets_explanation' => 'Widget yang aktif saat ini:',
		'add_category_button' => 'Tambah Kategori',
		'add_field_button' => 'Tambah Bidang',
		'add_link_button' => 'Tambah tautan',
		'add_link_link' => ' - ^1tambah tautan^2',
		'add_new_field' => 'Tambah bidang baru',
		'add_new_title' => 'Tambah judul baru',
		'add_page_button' => 'Tambah Laman',
		'add_title_button' => 'Tambah Judul',
		'add_widget_button' => 'Tambah Widget',
		'add_widget_link' => ' - ^1tambah widget^2',
		'admin_title' => 'Pusat Administrasi',
		'after_footer' => 'Setelah tautan pada kaki',
		'after_main_menu' => 'Setelah tab pada bagian atas',
		'after_x_tab' => 'Setelah tab "^"',
		'after_x' => 'Setelah "^"',
		'moderate_title' => 'Moderasi',
		'basic_editor' => 'Editor Dasar',
		'before_main_menu' => 'Sebelum tab pada bagian atas',
		'block_ips_note' => 'Gunakan tanda hubung untuk rentang atau * untuk mencocokkan angka. Contoh: 192.168.0.4 , 192.168.0.0-192.168.0.31 , 192.168.0.*',
		'block_words_note' => 'Gunakan * untuk mencocokkan huruf. Contoh: pel (hanya tepat cocok dengan pel) , pel* (cocok dengan pelihara atau pelaku) , pe*l (cocok dengan pensil atau pengambil).',
		'cancel_mailing_button' => 'Batalkan Pengiriman',
		'categories_introduction' => 'Untuk memulai dengan kategori, klik tombol \'Tambah Kategori\'.',
		'categories_not_shown' => 'Beberapa pertanyaan memiliki kategori yang tidak akan ditampilkan.',
		'categories_title' => 'Kategori',
		'categories' => 'Kategori',
		'category_add_sub' => 'tambah sub-kategori',
		'category_added' => 'Kategori ditambahkan',
		'category_already_used' => 'Sudah digunakan oleh kategori lain',
		'category_default_slug' => 'kategori-^',
		'category_description' => 'Deskripsi kategori opsional:',
		'category_max_depth_x' => 'Beberapa opsi mungkin disembunyikan untuk mencegah kategori melebihi ^ tingkat.',
		'category_move_parent' => 'pindahkan ke induk lain',
		'category_name_first' => 'Nama kategori pertama:',
		'category_name' => 'Nama kategori:',
		'category_no_add_subs_x' => 'Kategori ini tidak dapat memiliki sub-kategori karena sudah mencapai ^ tingkat.',
		'category_no_delete_subs' => 'Kategori ini tidak dapat dihapus karena memiliki sub-kategori.',
		'category_no_sub_error' => 'Ada ^q pertanyaan yang tidak memiliki sub-kategori - ^1tentukan sub-kategori^2',
		'category_no_sub_to' => 'Pindakan pertanyaan pada ^ yang tidak memiliki sub-kategori ke:',
		'category_no_subs' => 'Tidak ada',
		'category_none_error' => 'Ada ^q pertanyaan yang tidak memiliki kategori - ^1tentukan kategori^2',
		'category_none_to' => 'Pindakan pertanyaan yang tidak memiliki kategori ke:',
		'category_parent' => 'Kategori induk:',
		'category_saved' => 'Kategori disimpan',
		'category_slug' => 'Slug kategori - Fragmen URL:',
		'category_subs' => 'Sub-kategori:',
		'category_top_level' => 'Tanpa induk (tingkat teratas)',
		'characters' => 'karakter',
		'check_language_suffix' => ' - ^1periksa berkas bahasa^2',
		'click_name_edit' => 'Laman atau tautan suaian:',
		'database_cleanup' => 'Operasi pembersihan basis data',
		'delete_category_reassign' => 'Hapus kategori ini dan pindahkan pertanyaannya ke:',
		'delete_category' => 'Hapus kategori ini',
		'delete_field' => 'Hapus bidang ini',
		'delete_hidden_complete' => 'Semua kiriman tersembunyi yang tidak memiliki keterkaitan telah dihapus',
		'delete_hidden_note' => ' - semua pertanyaan, jawaban, dan komentar tersembunyi yang tidak memiliki keterkaitan',
		'delete_hidden' => 'Hapus kiriman tersembunyi',
		'delete_link' => 'Hapus tautan ini',
		'delete_page' => 'Hapus laman ini',
		'delete_stop' => 'Berhenti menghapus',
		'delete_title' => 'Hapus judul ini',
		'delete_widget_position' => 'Hapus widget dari posisi ini',
		'edit_custom_page' => 'Edit laman suaian',
		'edit_field' => ' - ^1edit bidang^2',
		'edit_link' => ' - ^1edit tautan^2',
		'edit_page' => ' - ^1edit laman^2',
		'edit_title' => ' - ^1edit judul^2',
		'emails_per_minute' => 'surel per menit',
		'emails_title' => 'Surel',
		'feed_link_example' => 'Umpan contoh',
		'feed_link' => 'Umpan',
		'feeds_title' => 'Umpan RSS',
		'field_link_url' => 'URL Terkait',
		'field_multi_line' => 'Teks baris banyak',
		'field_name' => 'Nama bidang:',
		'field_single_line' => 'Teks baris tunggal',
		'field_type' => 'Jenis konten:',
		'first' => 'Pertama',
		'flagged_title' => 'Tanda',
		'from_anon' => 'Dari anonim:',
		'from_users' => 'Dari pengguna:',
		'general_title' => 'Umum',
		'hidden_answers_deleted' => 'Menghapus ^1 dari ^2 jawaban tersembunyi tanpa keterkaitan ...',
		'hidden_comments_deleted' => 'Menghapus ^1 dari ^2 komentar tersembunyi...',
		'hidden_questions_deleted' => 'Menghapus ^1 dari ^2 pertanyaan tersembunyi tanpa keterkaitan ...',
		'hotness_factors' => 'Kepentingan relatif keseruan pertanyaan:',
		'hidden_title' => 'Penyembunyian',
		'installed_plugins' => 'Plugin terinstal:',
		'ip_address_pages' => 'Laman alamat IP',
		'layout_title' => 'Tata letak',
		'link_name' => 'Teks tautan:',
		'link_new_window' => 'Buka tautan pada jendela baru',
		'link_url' => 'URL tautan - absolut atau relatif terhadap akar Q2A:',
		'lists_title' => 'Daftar',
		'mailing_complete' => 'Pengiriman selesai',
		'mailing_explanation' => 'Pengguna dapat berhenti berlangganan pada laman akun mereka.',
		'mailing_progress' => 'Pengiriman selesai untuk ^1 dari ^2 pengguna...',
		'mailing_title' => 'Pengiriman',
		'mailing_unsubscribe' => 'Tautan untuk berhenti berlangganan akan ditambahkan pada bagian bawah setiap pesan.',
		'maintenance_admin_only' => 'Situs sedang dalam ^1pemeliharaan^2 dan tidak dapat diakses oleh pengguna reguler.',
		'maximum_x' => ' (maks. ^)',
		'module_x_database_init' => 'Modul ^1 ^2 memerlukan ^3inisiasi basis data^4.',
		'most_flagged_title' => 'Konten bertanda',
		'mysql_version' => 'Versi MySQL:',
		'nav_links_explanation' => 'Tampilkan tautan navigasi:',
		'nav_qa_is_home' => 'T&J (tautan ke beranda)',
		'neat_urls_note' => ' (memerlukan berkas ^1htaccess^2)',
		'no_approve_found' => 'Tidak ada konten yang perlu persetujuan',
		'no_classification' => 'Tidak ada',
		'no_flagged_found' => 'Tidak ada konten bertanda',
		'no_hidden_found' => 'Tidak ada konten tersembunyi',
		'no_image_gd' => 'Versi PHP terinstal dikompilasi tanpa dukungan gambar GD sehingga pengguna tidak dapat mengunggah avatar secara langsung.',
		'no_link' => 'Tanpa tautan',
		'no_multibyte' => 'Versi PHP terinstal dikompilasi tanpa dukungan dukungan multibyte string. Pencarian akan kurang efektif bagi karakter selain abjad Latin.',
		'no_plugin_options' => 'Plugin terinstal Anda tidak memiliki opsi untuk ditampilkan.',
		'no_privileges' => 'Hanya administrator yang dapat mengakses laman ini.',
		'not_logged_in' => 'Harap ^1masuk^2 sebagai administrator untuk mengakses laman ini.',
		'opposite_main_menu' => 'Ujung tab di bagian atas',
		'options_reset' => 'Opsi direset',
		'options_saved' => 'Opsi disimpan',
		'options' => 'opsi',
		'page_already_used' => 'Telah dipakai oleh suatu laman',
		'page_content_html' => 'Konten yang ditampilkan pada laman - HTML diizinkan:',
		'page_default_slug' => 'laman-^',
		'page_heading' => 'Kepala yang ditampilkan pada bagian atas laman:',
		'page_name' => 'Nama laman (juga digunakan untuk tab atau tautan):',
		'page_slug' => 'Slug laman (fragmen URL):',
		'pages_explanation' => 'Klik tombol \'Tambah Laman\' untuk menambah konten suaian pada situs Q2A Anda, atau \'Tambah Tautan\' untuk menautkan ke laman web lain.',
		'pages_title' => 'Laman',
		'pause_mailing_button' => 'Jeda Kiriman',
		'per_ip_hour' => 'per IP/jam',
		'per_user_hour' => 'per pengguna/jam',
		'permissions_title' => 'Akses',
		'permit_to_view' => 'Tampak bagi:',
		'php_version' => 'Versi PHP:',
		'pixels' => 'piksel',
		'plugin_module' => ' (modul plugin: ^)',
		'plugin_pages_explanation' => 'Laman disediakan oleh plugin:',
		'plugins_title' => 'Plugin',
		'points_defaults_shown' => 'Standar di bawah BELUM DITERAPKAN:',
		'points_required' => 'Poin untuk menerima gelar:',
		'points_title' => 'Poin',
		'points' => 'poin',
		'position' => 'Posisi:',
		'posting_title' => 'Kiriman',
		'profile_fields' => 'Bidang tambahan pada profil pengguna:',
		'q2a_build_date' => 'Tanggal build:',
		'q2a_db_size' => 'Besar basis data:',
		'q2a_db_version' => 'Versi basis data Q2A:',
		'q2a_latest_version' => 'Versi terakhir:',
		'q2a_version' => 'Versi Question2Answer:',
		'question_lists' => 'Daftar pertanyaan',
		'question_pages' => 'Laman pertanyaan',
		'recalc_categories_backpaths' => 'Menghitung ulang jejak URL bagi ^1 dari ^2 kategori ...',
		'recalc_categories_complete' => 'Semua kategori berhasil dihitung ulang.',
		'recalc_categories_note' => ' - untuk kategori kiriman dan jumlah kategori',
		'recalc_categories_recounting' => 'Menghitung ulang pertanyaan bagi ^1 dari ^2 kategori ...',
		'recalc_categories_updated' => 'Dihitung ulang bagi ^1 dari ^2 kiriman ...',
		'recalc_categories' => 'Hitung ulang kategori',
		'recalc_points_complete' => 'Semua nilai pengguna berhasil dihitung ulang.',
		'recalc_points_note' => ' - untuk peringkat pengguna dan tampilan poin',
		'recalc_points_recalced' => 'Dihitung ulang bagi ^1 dari ^2 pengguna ...',
		'recalc_points_usercount' => 'Mengestimasi jumlah total pengguna...',
		'recalc_points' => 'Hitung ulang poin pengguna',
		'recalc_posts_count' => 'Menghitung jumlah total pertanyaan, jawaban, dan komentar ...',
		'recalc_stop' => 'Hentikan hitung ulang',
		'recent_approve_title' => 'Konten terakhir yang menunggu persetujuan',
		'recent_hidden_title' => 'Konten terakhir yang disembunyikan',
		'recount_posts_as_recounted' => 'Menghitung ulang jawaban dan keseruan bagi ^1 dari ^2 kiriman ...',
		'recount_posts_complete' => 'Semua kiriman berhasil dihitung ulang.',
		'recount_posts_note' => ' - jumlah jawaban, suara, tanda, dan keseruan tiap kiriman',
		'recount_posts_stop' => 'Hentikan hitung ulang',
		'recount_posts_votes_recounted' => 'Menghitung ulang suara dan tanda bagi ^1 dari ^2 kiriman ...',
		'recount_posts' => 'Hitung ulang kiriman',
		'refill_events_complete' => 'Semua aliran peristiwa berhasil diisi ulang',
		'refill_events_note' => ' - untuk daftar pembaruan tiap pengguna',
		'refill_events_refilled' => 'Mengisi ulang bagi ^1 dari ^2 pertanyaan ...',
		'refill_events' => 'Isi ulang aliran peristiwa',
		'reindex_content' => 'Indeks ulang konten',
		'reindex_content_note' => ' - untuk pencarian dan penyaranan pertanyaan terkait',
		'reindex_content_stop' => 'Hentikan indeks ulang',
		'reindex_pages_reindexed' => 'Mengindeks ulang ^1 dari ^2 laman ...',
		'reindex_posts_complete' => 'Semua kiriman berhasil diindeks ulang.',
		'reindex_posts_reindexed' => "Mengindeks ulang ^1 dari ^2 kiriman ...",
		'reindex_posts_wordcounted' => 'Menghitung ulang ^1 dari ^2 kata ...',
		'requires_php_version' => 'Dinonaktifkan - perlu PHP ^ atau lebih baru',
		'requires_q2a_version' => 'Dinonaktifkan - perlu Question2Answer ^ atau lebih baru',
		'reset_options_button' => 'Reset ke Standar',
		'resume_mailing_button' => 'Lanjutkan Pengiriman',
		'save_options_button' => 'Simpan Opsi',
		'save_recalc_button' => 'Simpan dan Hitung Ulang',
		'send_test_button' => 'Kirim Pengujian kepada Saya',
		'show_defaults_button' => 'Tampilkan Standar',
		'slug_bad_chars' => 'Slug tidak dapat mengandung karakter berikut: ^',
		'slug_reserved' => 'Slug ini dicadangkan untuk dipakai laman lain',
		'spam_title' => 'Spam',
		'start_mailing_button' => 'Mulai Pengiriman',
		'stats_title' => 'Stat',
		'stop_recalc_warning' => 'Operasi pembersihan basis data sedang berjalan. Jika Anda menutup laman ini, operasi tersebut akan dihentikan.',
		'tag_pages' => 'Laman tag',
		'tags_and_categories' => 'Tag dan Kategori',
		'tags_not_shown' => 'Beberapa pertanyaan memiliki tag yang tidak akan ditampilkan.',
		'tags' => 'Tag',
		'test_sent_to_x' => 'Pesan pengujian telah dikirim kepada ^',
		'title_already_used' => 'Nilai ini telah digunakan oleh gelar lain',
		'top_level_categories' => 'Kategori tingkat teratas:',
		'total_as' => 'Jawaban total:',
		'total_cs' => 'Komentar total:',
		'total_qs' => 'Pertanyaan total:',
		'unnamed_plugin' => 'Plugin Tanpa Nama',
		'upgrade_db' => 'Basis data Question2Answer Anda perlu ^1ditingkatkan^2 untuk versi ini.',
		'url_format_note' => 'Opsi berlabel ^ dapat dipakai untuk konfigurasi situs Anda. Untuk optimisasi mesin pencarian (SEO) terbaik, gunakan opsi ^ pertama yang tersedia.',
		'user_pages' => 'Laman pengguna',
		'user_title' => 'Gelar pengguna - HTML diizinkan:',
		'user_titles' => 'Gelar pengguna berdasarkan poin:',
		'users_active' => 'Pengguna aktif:',
		'users_must_have' => 'Pengguna harus',
		'users_posted' => 'Pengguna dengan kiriman:',
		'users_registered' => 'Pengguna terdaftar:',
		'users_title' => 'Pengguna',
		'users_voted' => 'Pengguna yang memberi suara:',
		'version_get_x' => 'dapatkan ^',
		'version_requires_php' => '^1 memerlukan PHP ^2',
		'version_requires_q2a' => '^1 memerlukan Q2A ^2',
		'version_latest_unknown' => 'terakhir tidak diketahui',
		'version_latest' => 'terakhir',
		'viewing_title' => 'Tampilan',
		'widget_all_pages' => 'Tampilkan widget pada posisi ini di semua laman',
		'widget_global_options' => ' - ^1opsi^2',
		'widget_name' => 'Nama widget:',
		'widget_no_positions' => 'Widget ini telah ditambahkan pada semua posisi yang dimungkinkan.',
		'widget_not_available' => 'Widget ini tidak tersedia. Hal ini mungkin disebabkan karena plugin yang menyediakan widget ini sudah tidak terinstal.',
		'widget_pages_explanation' => 'Tampilkan widget pada posisi ini di laman berikut:',
		'widgets_explanation' => 'Widget yang tersedia:',
	);


/*
	Omit PHP closing tag to help avoid accidental output
*/